baseURL = "https://watsnew.dev/"
languageCode = "en-us"
title = "watsnew.dev"
theme = "PaperMod"
publishDir = "docs"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]publishDir
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3


